# Generated by Django 4.2 on 2026-06-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.URLField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
