# Generated by Django 4.2 on 2026-06-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='type',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.AddField(
            model_name='favorite',
            name='category',
            field=models.CharField(choices=[('movie', 'Movie'), ('sports', 'Sports'), ('restaurant', 'Restaurant'), ('event', 'Event')], default='movie', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
