# Generated by Django 6.0.6 on 2026-06-23 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_favorite_type_remove_favorite_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('promoter', 'Promoter')], default='customer', max_length=20)),
                ('promoter_type', models.CharField(blank=True, choices=[('theatre_owner', 'Theatre Owner'), ('restaurant_owner', 'Restaurant Owner'), ('stadium_owner', 'Stadium Owner'), ('music_concert_owner', 'Music Concert Owner'), ('standup_comedy_owner', 'Standup Comedy Owner')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
