# Generated by Django 6.0.6 on 2026-06-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_alter_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('location', models.CharField(max_length=200)),
                ('concert_date', models.CharField(max_length=100)),
                ('concert_time', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=20)),
                ('cast', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=50)),
                ('release_date', models.CharField(max_length=100)),
                ('show_time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('rating', models.CharField(max_length=20)),
                ('opening_hours', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SportsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('venue', models.CharField(max_length=200)),
                ('event_date', models.CharField(max_length=100)),
                ('event_time', models.CharField(max_length=50)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
