# Generated by Django 6.0.6 on 2026-06-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_concertbooking_moviebooking_restaurantbooking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantbooking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
